# Generated by Django 2.2.7 on 2019-11-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_lname', models.CharField(blank=True, max_length=64, null=True)),
                ('manager_fname', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_description', models.CharField(blank=True, max_length=64, null=True)),
                ('manager_id', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=64)),
                ('skill_description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_id', models.AutoField(primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_lname', models.CharField(max_length=64)),
                ('resource_fname', models.CharField(max_length=64)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Language')),
                ('timezone_id', models.ForeignKey(db_column='timezone_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Timezone')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_skill_level', models.DecimalField(decimal_places=0, max_digits=1, null=True)),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Resource')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Skill')),
            ],
            options={
                'unique_together': {('resource_id', 'skill_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Project')),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Resource')),
            ],
            options={
                'unique_together': {('resource_id', 'project_id')},
            },
        ),
    ]
