# Generated by Django 2.2.7 on 2019-12-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_hopper', '0002_auto_20191208_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceskill',
            name='resource_skill_level',
            field=models.DecimalField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('5', '4'), ('5', '5')], decimal_places=0, max_digits=1, null=True),
        ),
    ]
