# Generated by Django 2.2.7 on 2019-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_hopper', '0003_auto_20191208_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceskill',
            name='resource_skill_level',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
