# Generated by Django 2.2.7 on 2019-12-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_hopper', '0004_auto_20191208_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager_id',
            field=models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_hopper.Manager'),
        ),
    ]
