# Generated by Django 3.0 on 2019-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_hopper', '0005_auto_20191208_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_onteam',
            field=models.BooleanField(default=False),
        ),
    ]
